---
# tasks file for centos8-lemp
- name: install lemp packages
  yum:
    name: '{{ item }}'
    state: present
  loop:
  - nginx
  - firewalld
  - mariadb-server, mariadb, python3-PyMySQL
  - php, php-mysqlnd, php-fpm, php-opcache, php-gd, php-xml, php-mbstring

- name: start services
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
  - nginx
  - firewalld
  - mariadb
  - php-fpm

- name: open http/https firewall ports
  firewalld:
    zone: public
    service: '{{ item }}'
    immediate: true
    permanent: yes
    state: enabled
  loop:
  - http
  - https
  notify: restart firewalld

- name: make nginx owner of web directory
  file:
    path: /usr/share/nginx/html
    recurse: yes
    owner: nginx
    group: nginx

- name: change php user to nginx
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: '^{{ item.apache }}'
    line: '{{ item.nginx }}'
  loop:
  - user:
    apache: "user ="
    nginx: "user = nginx"
  - group: 
    apache: "group ="
    nginx: "group = nginx"
  notify: restart php

- name: listen on unix socket not tcp/ip
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: "listen ="
    line: "listen = /run/php-fpm/www.sock"
    state: present
  notify: restart php

- name: create php test page
  copy:
    dest: /usr/share/nginx/html/info.php
    content: "<?php phpinfo(); ?>"
    owner: nginx
    group: nginx
  notify:
  - restart nginx
  - restart php

- name: change root password
  mysql_user:
    name: root
    password: '{{ db_root_password }}'
    host_all: yes
  notify: restart mariadb

- name: apply /root/.my.cnf
  template:
    src: templates/my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600
    owner: root
    group: root
  notify: restart mariadb

- name: remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  notify: restart mariadb

- name: remove test database
  mysql_db:
    name: test
    state: absent
  notify: restart mariadb
