---
- name: change root password
  mysql_user:
    name: root
    password: '{{ db_root_password }}'
    host_all: yes
  notify: restart mariadb

- name: apply /root/.my.cnf
  template:
    src: templates/my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600
    owner: root
    group: root
  notify: restart mariadb

- name: remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  notify: restart mariadb

- name: remove test database
  mysql_db:
    name: test
    state: absent
  notify: restart mariadb
